package com.eahm.jetpackcomponentsexp.models

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import org.jetbrains.annotations.NotNull

/**
 * Entity model for the table "products"
 */
@Entity(tableName = "products")
data class Product(
    /**
     * Identification number.
     *
     * Is autogenerated and incremental.
     */
    @PrimaryKey(autoGenerate = true)
    @NotNull
    @ColumnInfo(name = "productId")
    val id : Int = 0,

    /**
     * Name of the product
     */
    @ColumnInfo(name = "productName")
    val name : String = "",

    /**
     * Total Amount of objects of this product
     */
    val quantity : Int = 0
)